project_id = "hqibtbdovjcocqgwqwbw"

[functions.chat]
verify_jwt = false

[functions.generate-title]
verify_jwt = false

[functions.claim-advent]
verify_jwt = false

[functions.elevenlabs-token]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false

[functions.redeem-invite-code]
verify_jwt = false

[functions.crossatrix-login]
verify_jwt = false

[functions.croins-proxy]
verify_jwt = false

[functions.check-ip-ban]
verify_jwt = false

[functions.deduct-image-credits]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.magic-hour-generate]
verify_jwt = false

[functions.queue-join]
verify_jwt = false

[functions.queue-worker]
verify_jwt = false
