
ALTER TABLE public.model_costs
  ADD COLUMN IF NOT EXISTS max_tool_calls INT NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS tool_switchmodel BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tool_croins BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tool_vip BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tool_credits BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tool_email BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tool_shares BOOLEAN NOT NULL DEFAULT false;
