
ALTER TABLE public.model_costs
  ADD COLUMN IF NOT EXISTS tool_ccvideo BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tool_ccpost BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tool_ccsong BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tool_ccstream BOOLEAN NOT NULL DEFAULT false;
